# Copyright 1999-2016 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.17.0

EAPI=8

DIST_AUTHOR="LEONT"
DIST_VERSION="0.009"


inherit perl-module

DESCRIPTION="A tiny CPAN uploader"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND="perl-gcpan/HTTP-Tiny-Multipart
	dev-perl/Mozilla-CA
	>=dev-perl/Net-SSLeay-1.880.0
	>=dev-perl/IO-Socket-SSL-2.66.0
	dev-perl/TermReadKey
	dev-lang/perl"
