# Copyright 1999-2016 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.16.9

EAPI=8

MODULE_AUTHOR="ANDYA"
MODULE_VERSION="0.26"


inherit perl-module

DESCRIPTION="Create and parse GPX files."

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND="dev-perl/HTML-Parser
	dev-perl/DateTime-Format-ISO8601
	dev-perl/DateTime
	>=dev-perl/XML-Descent-1.40.0
	dev-perl/Module-Build
	dev-lang/perl"
