# Copyright 1999-2016 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.17.0

EAPI=8

DIST_AUTHOR="GOCCY"
DIST_VERSION="0.23"


inherit perl-module

DESCRIPTION="Lexical Analyzer for Perl5"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND=">=dev-perl/Module-Build-XSUtil-0.180.0
	dev-perl/Module-Build
	dev-lang/perl"
