# Copyright 1999-2016 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.16.9

EAPI=8

DIST_AUTHOR="EXIFTOOL"
DIST_VERSION="11.70"


inherit perl-module

DESCRIPTION="Read and write meta information"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND="perl-gcpan/POSIX-strptime
	dev-perl/Archive-Zip
	dev-lang/perl"
