# Copyright 1999-2016 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.17.0

EAPI=8

DIST_AUTHOR="DAGOLDEN"
DIST_VERSION="0.0019"


inherit perl-module

DESCRIPTION="Load (and optionally decrypt via GnuPG) user/pass identity information"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND="dev-perl/Test-Deep
	dev-perl/File-HomeDir
	dev-perl/IPC-Run
	dev-perl/File-Which
	dev-lang/perl"
