# Copyright 1999-2016 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.17.0

EAPI=5

MODULE_AUTHOR="PEVANS"
MODULE_VERSION="0.08"


inherit perl-module

DESCRIPTION="C<Future::IO> - Future-returning IO methods"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND="perl-gcpan/Struct-Dumb
	dev-perl/Module-Build
	perl-gcpan/Future
	perl-gcpan/Test-Identity
	dev-lang/perl"
