# Copyright 1999-2016 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.17.0

EAPI=5

MODULE_AUTHOR="PEVANS"
MODULE_VERSION="0.26"


inherit perl-module

DESCRIPTION="C<Syntax::Keyword::Try> - a C<try/catch/finally> syntax for perl"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND=">=perl-gcpan/XS-Parse-Keyword-0.21
	dev-perl/Module-Build
	dev-lang/perl"
