# Copyright 1999-2022 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.17.0

EAPI=8

DIST_AUTHOR="ISHIGAKI"
DIST_VERSION="0.20"


inherit perl-module

DESCRIPTION="parses local .pm files as PAUSE does"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND=">=dev-perl/Test-UseAllModules-0.170.0
	>=perl-gcpan/Parse-PMFile-0.47
	dev-lang/perl"
