# Copyright 1999-2022 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.17.0

EAPI=8

DIST_AUTHOR="PEVANS"
DIST_VERSION="0.36"


inherit perl-module

DESCRIPTION="C<XS::Parse::Keyword> - XS functions to assist in parsing keyword syntax"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND=">=dev-perl/ExtUtils-CChecker-0.110.0
	dev-perl/Module-Build
	dev-perl/Test2-Suite
	dev-lang/perl"
