# Copyright 1999-2024 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.17.0

EAPI=8

DIST_AUTHOR="BLUEFEET"
DIST_VERSION="0.10"

inherit perl-module

DESCRIPTION="Create, compare, and convert measurements."

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND=">=dev-perl/Module-Build-Tiny-0.46.0
	virtual/perl-Test-Simple
	>=dev-perl/Sub-Exporter-0.989.0
	dev-perl/Module-Build
	dev-lang/perl"
