# Copyright 1999-2023 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.16.9

EAPI=8

DIST_AUTHOR="DAVIDO"
DIST_VERSION="0.25"


inherit perl-module

DESCRIPTION="Binary Search within a sorted array."

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND="perl-gcpan/List-BinarySearch-XS
	dev-lang/perl"
