# Copyright 1999-2016 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.17.0

EAPI=8

DIST_AUTHOR="PEVANS"
DIST_VERSION="0.09"


inherit perl-module

DESCRIPTION="C<IO::Termios> - supply F<termios(3)> methods to C<IO::Handle> objects"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND="dev-perl/Module-Build
	dev-perl/IO-Tty
	dev-perl/Test-LongString
	dev-lang/perl"
