# Copyright 1999-2016 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.17.0

EAPI=5

MODULE_AUTHOR="SYBER"
MODULE_VERSION="1.2.16"


inherit perl-module

DESCRIPTION="ExtUtils::MakeMaker based module installer for XS modules."

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND="dev-perl/Test-Deep
	dev-lang/perl"
