# Copyright 1999-2022 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.17.0

EAPI=8

DIST_AUTHOR="SYBER"
DIST_VERSION="1.3.5"


inherit perl-module

DESCRIPTION="ExtUtils::MakeMaker based module installer for XS modules."

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND="dev-perl/Test-Deep
	>=perl-gcpan/PkgConfig-0.25026
	dev-lang/perl"
