# Copyright 1999-2016 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.16.9

EAPI=8

MODULE_AUTHOR="GOZER"
MODULE_VERSION="0.13"


inherit perl-module

DESCRIPTION="Perl extension to the POSIX date parsing strptime(3) function"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND="dev-lang/perl"
