# Copyright 1999-2016 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.17.0

EAPI=5

MODULE_AUTHOR="OVID"
MODULE_VERSION="0.02"


inherit perl-module

DESCRIPTION="\"split\" on steroids"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND="dev-perl/Module-Build
	>=dev-perl/Sub-Uplevel-0.280.0
	>=dev-perl/Test-Exception-0.430.0
	dev-lang/perl"
