# Copyright 1999-2022 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.17.0

EAPI=8

DIST_AUTHOR="BDFOY"
DIST_VERSION="0.22"


inherit perl-module

DESCRIPTION="Find a minimum required version of perl for Perl code"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND="dev-perl/Module-Build
	>=dev-perl/Compiler-Lexer-0.230.0
	>=dev-perl/Module-Build-Tiny-0.52.0
	dev-lang/perl"
