# Copyright 1999-2016 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.17.0

EAPI=5

MODULE_AUTHOR="TOKUHIROM"
MODULE_VERSION="0.19"


inherit perl-module

DESCRIPTION="Find a minimum required version of perl for Perl code"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND="dev-perl/Module-Build
	>=dev-perl/Module-Build-Tiny-0.39.0
	>=perl-gcpan/Compiler-Lexer-0.23
	dev-lang/perl"
