# Copyright 1999-2016 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.17.0

EAPI=5

MODULE_AUTHOR="TOKUHIROM"
MODULE_VERSION="v0.4.0"


inherit perl-module

DESCRIPTION="Pure perl spelling checker implementation"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND="dev-perl/Module-Build
	dev-perl/File-ShareDir
	dev-perl/Regexp-Common
	dev-lang/perl"
