# Copyright 1999-2016 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.17.0

EAPI=5

MODULE_AUTHOR="SKAJI"
MODULE_VERSION="0.07"


inherit perl-module

DESCRIPTION="tests module permissions in your distribution"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND=">=perl-gcpan/PAUSE-Permissions-0.17
	perl-gcpan/PAUSE-Permissions-MetaCPAN
	perl-gcpan/Config-Identity
	>=dev-perl/Test-UseAllModules-0.170.0
	>=perl-gcpan/Parse-LocalDistribution-0.19
	>=perl-gcpan/Parse-PMFile-0.42
	dev-lang/perl"
