# Copyright 1999-2016 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.17.0

EAPI=8

DIST_AUTHOR="PEVANS"
DIST_VERSION="0.47"


inherit perl-module

DESCRIPTION="C<Future> - represent an operation awaiting completion"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND="dev-perl/Module-Build
	perl-gcpan/Test-Identity
	dev-perl/Test-Fatal
	perl-gcpan/Test-Refcount
	dev-lang/perl"
