# Copyright 1999-2016 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.17.0

EAPI=5

MODULE_AUTHOR="TOKUHIROM"
MODULE_VERSION="0.04"


inherit perl-module

DESCRIPTION="does your code require newer perl than you think?"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND="dev-perl/File-Find-Rule
	>=perl-gcpan/Perl-MinimumVersion-Fast-0.19
	dev-perl/Module-Build
	dev-perl/Test-MinimumVersion
	>=dev-perl/YAML-Tiny-1.730.0
	dev-perl/File-Find-Rule-Perl
	dev-lang/perl"
