# Copyright 1999-2022 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.17.0

EAPI=8

DIST_AUTHOR="SYBER"
DIST_VERSION="2.0.1"


inherit perl-module

DESCRIPTION="Run C++ catch tests from perl test file"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND=">=perl-gcpan/XS-libcatch-3.0.1
	>=perl-gcpan/XS-Install-1.3.5
	dev-perl/Test-Deep
	dev-lang/perl"
