# Copyright 1999-2016 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.17.0

EAPI=5

MODULE_AUTHOR="PEVANS"
MODULE_VERSION="0.06"


inherit perl-module

DESCRIPTION="C<Convert::Color::XTerm> - indexed colors used by XTerm"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND="dev-perl/Module-Build
	>=dev-perl/Convert-Color-0.110.0
	dev-lang/perl"
