# Copyright 1999-2016 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.17.0

EAPI=8

DIST_AUTHOR="SKAJI"
DIST_VERSION="0.001"


inherit perl-module

DESCRIPTION="get module permissions from MetaCPAN API"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND=">=dev-perl/Module-Build-Tiny-0.39.0
	>=dev-perl/IO-Socket-SSL-2.66.0
	dev-perl/Module-Build
	dev-lang/perl"
