# Copyright 1999-2024 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.17.0

EAPI=8

DIST_AUTHOR="PEVANS"
DIST_VERSION="0.06"

inherit perl-module

DESCRIPTION="C<Test::Future::IO> - unit testing on C<Future::IO>"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND=">=dev-perl/Test-ExpectAndCheck-0.06
	virtual/perl-Test2-Suite
	dev-perl/Module-Build
	perl-gcpan/Future-Buffer
	dev-perl/Test-Deep
	dev-perl/Future-IO
	dev-lang/perl"
