# Copyright 1999-2016 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.16.9

EAPI=8

MODULE_AUTHOR="ANDYA"
MODULE_VERSION="v0.0.4"


inherit perl-module

DESCRIPTION="Easy setting, getting of an image's location information"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND=">=media-libs/exiftool-11.70
	dev-lang/perl"
